{
 "title": "Performance Metrics - Pulsar",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "I/O throughput + Producer/Consume Throughput",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "Bps", "label": "Throughput" }
   ],
   "targets": [
    { "expr": "sum(pulsar_throughput_in)", "legendFormat": "Produce rate" },
    { "expr": "sum(pulsar_throughput_out)", "legendFormat": "Consume rate" },
    {
     "expr": "sum(rate(bookie_WRITE_BYTES[30s]))",
     "legendFormat": "Bookie Add Entry Rate"
    },
    {
     "expr": "avg(bookkeeper_server_ADD_ENTRY_REQUEST{success=\"true\", quantile=\"0.99\"})",
     "legendFormat": "Bookie Add Entry Latency (p99)"
    }
   ]
  },
  {
   "title": "Journal Callback Queue Length",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Entries" }
   ],
   "targets": [
    {
     "expr": "bookie_journal_JOURNAL_CB_QUEUE_SIZE",
     "legendFormat": "Number of entries - {{instance}}"
    }
   ]
  },
  {
   "title": "I/O Utilization",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "delta(node_disk_io_time_seconds_total{device=~\"nvme1n1|nvme2n1\"}[1m])/60",
     "legendFormat": "Broker - {{instance}} ➝ Disk - {{device}}"
    }
   ]
  },
  {
   "title": "I/O throughput",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum by (instance) (delta(node_disk_written_bytes_total{device=~\"nvme1n1|nvme2n1\"}[1m])/60)",
     "legendFormat": "Broker - {{instance}}"
    }
   ]
  },
  {
   "title": "Publish rate (messages/sec)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(delta(benchmark_producer_messages_sent[1m])/60)"
    }
   ]
  },
  {
   "title": "Publish throughput (MB/sec)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(delta(benchmark_producer_bytes_sent[1m])/60)"
    }
   ]
  },
  {
   "title": "Log Flush Time (p99)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "rate(kafka_log_logflushstats_logflushrateandtimems{quantile=\"0.99\"}[1m])",
     "legendFormat": "Broker - {{instance}}"
    }
   ]
  },
  {
   "title": "CPU Usage across all Brokers",
   "type": "graph",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "short", "label": "percentage" }
   ],
   "targets": [
    {
     "expr": "sum by (mode)(irate(node_cpu_seconds_total{mode=\"user\"}[5m])) * 100",
     "legendFormat": "User - Normal processes executing in user mode"
    },
    {
     "expr": "sum by (mode)(irate(node_cpu_seconds_total{mode=\"system\"}[5m])) * 100",
     "legendFormat": "System - Processes executing in kernel mode"
    },
    {
     "expr": "sum by (mode)(irate(node_cpu_seconds_total{mode=\"iowait\"}[5m])) * 100",
     "legendFormat": "Iowait - Waiting for I/O to complete"
    },
    {
     "expr": "sum by (mode)(irate(node_cpu_seconds_total{mode=\"softirq\"}[5m])) * 100",
     "legendFormat": "Softirq - Servicing softirqs"
    },
    {
     "expr": "sum by (mode)(irate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100",
     "legendFormat": "Idle - Waiting for something to happen"
    }
   ]
  }
 ]
}