#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

name: RabbitMQ
driverClass: io.openmessaging.benchmark.driver.rabbitmq.RabbitMqBenchmarkDriver

# RabbitMq client specific configurations
brokers:
{% for worker in groups['rabbitmq'] %}
  - {{ hostvars[worker].private_ip }}
{% endfor %}
messagePersistence: true
queueType: CLASSIC # CLASSIC | QUORUM
exchangeType: DIRECT # DIRECT | TOPIC | FANOUT | HEADERS
topicPrefix: summit
exclusive: false # Turn off for HA/durability to take effect
singleNode: false # Turn on to use a single node for all queues/exchanges for all producers/consumers