{
 "title": "Performance Metrics - RabbitMQ",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Producer/Consume Throughput + CPU Usage",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "Bps", "label": "I/O throughput" }
   ],
   "targets": [
    {
     "expr": "sum(rate(benchmark_producer_bytes_sent[1m]))",
     "legendFormat": "Produce rate"
    },
    {
     "expr": "sum(rate(benchmark_consumer_bytes_recv[1m]))",
     "legendFormat": "Consume rate"
    },
    {
     "expr": "(((count(count(avg(node_cpu_seconds_total)) by (cpu))) - avg(sum by (mode)(avg(irate(node_cpu_seconds_total{mode='idle'}[5m]))))) * 100) / count(count(avg(node_cpu_seconds_total)) by (cpu))",
     "legendFormat": "CPU Usage"
    }
   ]
  },
  {
   "title": "I/O throughput",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum by (instance) (delta(node_disk_written_bytes_total{device=~\"nvme1n1|nvme2n1\"}[1m])/60)",
     "legendFormat": "Broker - {{instance}}"
    }
   ]
  },
  {
   "title": "Publish throughput (MB/sec)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(delta(benchmark_producer_bytes_sent[1m])/60)"
    }
   ]
  },
  {
   "title": "I/O Utilization",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "delta(node_disk_io_time_seconds_total{device=~\"nvme1n1|nvme2n1\"}[1m])/60",
     "legendFormat": "Broker - {{instance}} ➝ Disk - {{device}}"
    }
   ]
  },
  {
   "title": "Publish rate (messages/sec)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(delta(benchmark_producer_messages_sent[1m])/60)"
    }
   ]
  },
  {
   "title": "Log Flush Time (p99)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "rate(kafka_log_logflushstats_logflushrateandtimems{quantile=\"0.99\"}[1m])",
     "legendFormat": "Broker - {{instance}}"
    }
   ]
  },
  {
   "title": "CPU Usage across all Brokers",
   "type": "graph",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "short", "label": "percentage" }
   ],
   "targets": [
    {
     "expr": "sum by (mode)(irate(node_cpu_seconds_total{mode=\"user\"}[5m])) * 100",
     "legendFormat": "User - Normal processes executing in user mode"
    },
    {
     "expr": "sum by (mode)(irate(node_cpu_seconds_total{mode=\"system\"}[5m])) * 100",
     "legendFormat": "System - Processes executing in kernel mode"
    },
    {
     "expr": "sum by (mode)(irate(node_cpu_seconds_total{mode=\"iowait\"}[5m])) * 100",
     "legendFormat": "Iowait - Waiting for I/O to complete"
    },
    {
     "expr": "sum by (mode)(irate(node_cpu_seconds_total{mode=\"softirq\"}[5m])) * 100",
     "legendFormat": "Softirq - Servicing softirqs"
    },
    {
     "expr": "sum by (mode)(irate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100",
     "legendFormat": "Idle - Waiting for something to happen"
    }
   ]
  }
 ]
}